#cloud-config
#chpasswd:
#  list: |
#     root:passw0rd
#     ubuntu:passw0rd
#  expire: False
ssh_pwauth: True
ssh_authorized_keys:
  - {{ssh_authorized_key}}
bootcmd:
  - echo "ssh key set for user ubuntu"
