apiVersion: v1
baseDomain: {{domain}}
metadata:
  name: {{cluster}}
networking:
  clusterNetwork:
  - cidr: 192.168.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: {{subnet}}.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: {{count - 3}}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: '{{ssh_authorized_key}}'
