# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

- name: create aws role
  community.aws.iam_role:
    name: eksClusterRole
    description: EKS Cluster Role
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    managed_policies:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  register: role

- debug: msg="{{role.arn}}"

- name: create aws vpc
  amazon.aws.ec2_vpc_net:
    name: "{{cluster}}_vpc"
    cidr_block: "{{subnet}}.0/16"
  register: vpc

- debug: msg="{{vpc.id}}"

- name: create aws subnet 
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{vpc.is}}"
    cidr: "{{subnet}}.0/24"
  register: subnet

- debug: msg="{{subnet.id}}"


#- name: Create an EKS cluster
#  community.aws.aws_eks_cluster:
#    name: my_cluster
#    version: 1.14
#    role_arn: my_eks_role
#    subnets:
#      - subnet-aaaa1111
#    security_groups:
#      - my_eks_sg
#      - sg-abcd1234
#  register: caller_facts