- name: apt-get update 
  apt: 
    update_cache: yes 
    autoremove: yes
- name: apt-get upgrade
  apt:
     name: '*'
     state: latest
     force_apt_get: true
- name: install prerequisites
  apt: name={{item}} 
  with_items:
     - apt-transport-https 
     - ca-certificates
     - curl
     - software-properties-common
     - qemu-kvm 
     - libvirt-daemon-system
     - python3-pip
     - pkg-config
     - python3-dev
     - libvirt-dev
- pip: name=libvirt-python state=present