- name: apt-get update 
  apt: 
    update_cache: yes 
    autoremove: yes
- name: apt-get upgrade
  apt:
    name: '*'
    state: latest
    force_apt_get: true
- name: install prerequisites
  apt: name={{item}} 
  with_items:
    - software-properties-common
    - apt-transport-https 
    - ca-certificates
    - curl
    - python3-pip
    - python3-dev
    - python3-lxml
    - pkg-config
    - qemu-kvm 
    - libvirt-dev
    - libvirt-daemon-system
    - dnsmasq
- name: install python libraries
  pip: state=present name={{item}}
  with_items:
     - libvirt-python

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes