- name: apt-get update 
  apt: 
    update_cache: yes 
    autoremove: yes

- name: apt-get upgrade
  apt:
    name: '*'
    state: latest
    force_apt_get: true

- name: install ubuntu packages
  apt: name={{item}} 
  with_items:
    - software-properties-common
    - apt-transport-https 
    - ca-certificates
    - curl
    - python3-pip
    - python3-dev
    - python3-lxml
    - pkg-config
    - qemu-kvm 
    - libvirt-dev
    - libvirt-daemon-system
    - dnsmasq

- name: install python libraries
  pip: state=present name={{item}}
  with_items:
     - libvirt-python

- name: enable forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: cluster directory
  file: 
   path: "{{virt_dir}}/{{cluster}}"
   state: directory
   mode: 0755

- name: download base image
  get_url:
   url: '{{image_url}}'
   dest: "{{virt_dir}}/{{cluster}}/base.img"
