- set_fact:
    host: "{{item}}"
    id: "{{hostvars[item].id}}"
    prefix: "{{virt_dir}}/{{cluster}}/{{cluster}}{{hostvars[item].id}}"
    hostname: "{{hostvars[item].hostname}}"
    disk_size: "{{hostvars[item].disk_size}}"
    mem_size: "{{hostvars[item].mem_size}}"
    mac_addr: "{{hostvars[item].mac_addr}}"
    vcpu_num: "{{hostvars[item].vcpu_num}}"
  
- name: copy and resize image
  shell: >
    cp {{virt_dir}}/{{base_image}} {{prefix}}.img ;
    qemu-img resize {{prefix}}.img {{disk_size}}G
  args:
    creates: '{{prefix}}.img'

- name: generate user-data (cloud-init)
  template:
    src: "{{cluster_type}}.yml"
    dest: "{{prefix}}.yml"

- name: generate meta-data (hostname)
  template:
    src: "meta-data.txt"
    dest: "{{prefix}}.txt"

- name: build boot iso
  shell: >
    cloud-localds "{{prefix}}.iso" "{{prefix}}.yml" "{{prefix}}.txt"

- name: libvirt udefine vm
  community.libvirt.virt:
    command: undefine
    name: "{{hostname}}"
  ignore_errors: true

- name: create vm definition
  shell: > 
    virt-install 
    --name {{hostname}}
    --ram $(expr {{mem_size}} \* 1024) 
    --vcpu {{vcpu_num}}
    --disk path={{prefix}}.img 
    --disk path={{prefix}}.iso,device=cdrom 
    --os-type linux
    --os-variant {{os_variant}}
    --network bridge=virbr1,mac={{mac_addr}} 
    --graphics none 
    --console pty,target_type=serial
    --print-xml
  register: vm_xml

- name: write vm xml
  copy:
    dest: '{{prefix}}.xml'
    content: '{{vm_xml.stdout}}'

- name: libvirt define vm
  community.libvirt.virt:
    command: define
    xml: '{{vm_xml.stdout}}'
    autostart: yes

- name: start vm
  community.libvirt.virt:
    command: start
    name: "{{hostname}}"
